name: domain
description: A new Flutter project.
version: 1.0.0
publish_to: 'none' 

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  clean_architecture:
    path: ../clean_architecture
