name: Check formatting, Analyze, Test & Build
on:
  push:

jobs:
  setup_flutter:
    name: Check formatting, Analyze, Test & Build
    runs-on: ubuntu-latest
    environment: debug
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: '3.13.6'
         channel: 'stable'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        # flutter version
        with:
          flutter-version: '3.13.6'
          channel: 'stable'

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: dart format --set-exit-if-changed --output none .

      # Statically analyze the Dart code for any errors.
      # - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # Build apk.
      #- run: flutter build apk
      - name: Decode Keystore
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'release.jks'
          fileDir: './android/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build
        run: flutter build apk --release 
        env:
          ANDROID_KEYSTORE_PATH: ${{ steps.write_file.outputs.filePath }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Deploy
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          releaseNotes: "New release version"
          file: build/app/outputs/apk/release/app-release.apk
